from app import db
from datetime import datetime

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120), index=True)
    content = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    likes = db.Column(db.Integer, default=0)
    # Header image URL generated by Nano Banana
    header_image_url = db.Column(db.String(255))

    def to_dict(self):
        return {
            'id': self.id,
            'title': self.title,
            'content': self.content,
            'timestamp': self.timestamp.isoformat(),
            'likes': self.likes,
            'header_image_url': self.header_image_url
        }

class VisitorStats(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    page_viewed = db.Column(db.String(120))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    visitor_ip = db.Column(db.String(50)) # Hashed or anonymized ideally

    def to_dict(self):
        return {
            'id': self.id,
            'page_viewed': self.page_viewed,
            'timestamp': self.timestamp.isoformat()
        }
